### PR TITLE
Add wrapper and move the plugin files into a source folder

### PR DESCRIPTION
**Pull request by Nava2**
I got the Umple files loading in gradle. 👍 

This is a good start, but I haven't actually tested it.. but this is a good start. 

I also added a gradle wrapper.

### CODE REVIEW

**Comment by vahdat-ab** [comment]
@ahochheiden I think you should have the files but you may need to clean it up and customize it for this project. There might be many good things but not so much related to the project. 
@Nava2  If this is a copy from another open source we need to make sure it is referred and also it is compatible. 
I think it's better to rewrite the code based on these practices to be in a safe side.

**Comment by Nava2** [comment]
Oh, it's not. I looked at other MIT projects for how they structured folders, it mirrors a traditional Gradle project. The Gradle docs are frighteningly lacking in examples. 

Most of the code was actually generated by IntelliJ IDEA. 😄

**Comment by vahdat-ab** [comment]
I think that's the reason I said it's better to clean it up based on needs. If, for example, someone develops the same structure with Gradle plugin for Eclipse they might come up with different practices. 
I think it is better to go with modern structures of Gradle if it is possible (or available) so as not to have issues in near future. These projects used to change the old techniques really fast.
Let's keep this and go head to see how it goes :-)

**Comment by Nava2** [comment]
@ahochheiden any updates on this?

**Comment by ahochheiden** [comment]
Sorry, was doing programming contest stuff all day.

I looked through your changes, but I wasn't really sure what you did differently from what I tried initially that didn't work (The runtime/compile stuff). The only difference is that you made it a standadlone project, where mine was just in a build script (But that shouldn't really matter)

The other difference is that you have the gradleAPI and groovy specified as dependencies, which I'm thinking is what I was missing.

I wanted to understand why what you did worked and what I didn't before I merged it in.

**Comment by ahochheiden** [comment]
I went through it again and then did some testing on what I had originally, and my initial assumption was correct. The gradleApi and localGroovy dependencies were what was missing in my attempt.

**Pull request merged**
